server:
  error:
    include-stacktrace: never

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:accesskey}
        secret-key: ${AWS_SECRET_KEY:secretkey}
      region:
        static: ${AWS_REGION:us-east-1}
  application:
    name: customer-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/customer}
    username: ${DB_USER:admin}
    password: ${DB_PASS:123456}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    placeholder-replacement: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    enabled: true
    try-it-out-enabled: true
    filter: true
    persist-authorization: true

management:
  endpoints:
    web:
      base-path: /
